### ISSUE TITLE
Clarify `Database::basic` vs. `DatabaseRef::basic`

### ISSUE THREAD

**Issue by mattsse** [bluealloy/revm#200]
I bumped revm in foundry and fixed all breaking changes, but my tests started failing

after some debugging I noticed something here:

https://github.com/bluealloy/revm/blob/8f01d8609a4d829bd9994941a7fff920e9af4f88/crates/revm/src/db/in_memory_db.rs#L226

this will create a new `DbAccount` entry and mark it as non-existing

https://github.com/bluealloy/revm/blob/8f01d8609a4d829bd9994941a7fff920e9af4f88/crates/revm/src/db/in_memory_db.rs#L223

and will always return `None` for the `AccountInfo` if the state is non-existing

however with following pattern:

```rust
let mut info = Database::basic(&mut self, address)?.unwrap_or_default();
info.balance = balance;
self.insert_account(address, info);
```

another `Database::basic(&mut self, address)` will still return `None` because `insert_account` does not update the state.

this was a bit suprising because 

```rust
let mut info = DatabaseRef::basic(&self, address)?.unwrap_or_default();
info.balance = balance;
self.insert_account(address, info);
```

would return the `info` without additional state check:

https://github.com/bluealloy/revm/blob/8f01d8609a4d829bd9994941a7fff920e9af4f88/crates/revm/src/db/in_memory_db.rs#L285

so now I'm wondering whether I shouldn't use `Database::basic(&mut` at all

**Comment by rakita** [comment]
`load_account` will mark the account as `NotExisting` only if internal `Database` returns `None`, this seems like correct behaviour, `DatabaseRef` should do the same (will change that behaviour).

In both cases, it should be `None`, does this fixes the problem @mattsse? I am assuming that the bug is that info in `DatabaseRef `preserves the `NonExisting` while with `Database` with call of `unwrap_or_default`, `AccountState` will be set  to `None`.

**Comment by mattsse** [comment]
I think that should do it.

thanks!
